dataset:
  _dir: 'dataset/kkbox'
  members_path: ${dataset._dir}/members_small.csv
  songs_path: ${dataset._dir}/../songs_merged_small.csv
  train_path: ${dataset._dir}/train.csv
  test_path: ${dataset._dir}/test.csv

processed_data_path: 'processed_data.csv'
model_path: 'lightgbm_model.txt'