dataset:
  _dir: 'dataset/kkbox'
  # small_suffix: '_small'
  small_suffix: ''
  members_path: ${dataset._dir}/members${dataset.small_suffix}.csv
  songs_path: ${dataset._dir}/../songs_merged${dataset.small_suffix}.csv
  train_path: ${dataset._dir}/train.csv
  test_path: ${dataset._dir}/test${dataset.small_suffix}.csv

processed_data_path: 'processed_data.csv'
model_path: 'lightgbm_model.txt'
submission_path: 'submission.csv'